import { test, expect } from "@playwright/test";
import { hasTestDb, NO_DB_REASON, assertNotProduction, serviceClient } from "./fixtures/supabase";
import { createMember, deleteMember, uniqueEmail, type TestMember } from "./fixtures/members";

/**
 * Password reset.
 *
 * The token path is exercised with a REAL recovery link generated by the
 * service role (generateLink), rather than reading email. That keeps the test
 * hermetic while still driving the same fragment-parsing code a real link hits.
 */

test.describe("reset request — enumeration safety", () => {
  test.skip(!hasTestDb, NO_DB_REASON);
  test.beforeAll(() => assertNotProduction());

  /**
   * The confirmation must be byte-identical for a registered and an
   * unregistered address. Any difference — wording, timing hint, an extra line
   * — turns the form into a membership oracle, and for an alumni directory the
   * membership list is the asset worth protecting.
   */
  test("registered and unregistered addresses produce the same confirmation", async ({
    page,
  }) => {
    const member = await createMember({ status: "approved", emailPrefix: "enum" });
    try {
      const submit = async (email: string) => {
        await page.goto("/connect/forgot-password");
        await page.getByLabel("Email").fill(email);
        await page.getByRole("button", { name: /Send reset link/ }).click();
        await expect(page.getByText(/Check your email/i)).toBeVisible({
          timeout: 15000,
        });
        // Strip the echoed address itself, which necessarily differs.
        return (await page.locator("main").innerText()).replace(email, "<EMAIL>");
      };

      const registered = await submit(member.email);
      const unknown = await submit(uniqueEmail("definitely-not-registered"));

      expect(
        unknown,
        "an unregistered address must be indistinguishable from a registered one"
      ).toBe(registered);
    } finally {
      await deleteMember(member);
    }
  });
});

test.describe("reset request — rate limiting", () => {
  test.skip(!hasTestDb, NO_DB_REASON);

  /**
   * Validate-before-limit (DECISIONS #12). Malformed input must not consume
   * quota — that exact bug shipped once on the contact form, where three
   * rejected submissions locked the sender out for an hour.
   *
   * Runs against a unique-ish IP-keyed bucket; the limiter is per-process and
   * in-memory, which is why the suite runs serially.
   */
  test("malformed requests do not consume quota, and the 4th valid one is limited", async ({
    request,
    baseURL,
  }) => {
    for (let i = 0; i < 5; i++) {
      const res = await request.post(`${baseURL}/api/connect/reset-guard`, {
        data: { email: "not-an-email" },
      });
      expect(res.status(), `malformed attempt ${i + 1} must be 422`).toBe(422);
    }

    for (let i = 0; i < 3; i++) {
      const res = await request.post(`${baseURL}/api/connect/reset-guard`, {
        data: { email: uniqueEmail("ratelimit") },
      });
      expect(res.ok(), `valid attempt ${i + 1} should pass`).toBe(true);
    }

    const fourth = await request.post(`${baseURL}/api/connect/reset-guard`, {
      data: { email: uniqueEmail("ratelimit") },
    });
    expect(fourth.status(), "the 4th valid request must be limited").toBe(429);
    expect(await fourth.text()).not.toContain("{");
  });
});

test.describe("reset page states", () => {
  test.skip(!hasTestDb, NO_DB_REASON);

  test("no token shows the expired state, not a password form", async ({ page }) => {
    await page.goto("/connect/reset-password");

    await expect(page.getByRole("heading", { name: /expired/i })).toBeVisible({
      timeout: 15000,
    });
    // Offering a form that cannot possibly work is worse than saying so.
    await expect(page.locator('input[type="password"]')).toHaveCount(0);
    await expect(page.getByRole("link", { name: /Request a new link/i })).toBeVisible();
  });

  test("an invalid token also shows the expired state", async ({ page }) => {
    await page.goto(
      "/connect/reset-password#access_token=not-a-real-token&type=recovery"
    );
    await expect(page.getByRole("heading", { name: /expired/i })).toBeVisible({
      timeout: 15000,
    });
  });
});

test.describe("reset with a real recovery token", () => {
  test.skip(!hasTestDb, NO_DB_REASON);
  test.beforeAll(() => assertNotProduction());

  let member: TestMember;

  test.beforeEach(async () => {
    member = await createMember({ status: "approved", emailPrefix: "recovery" });
  });
  test.afterEach(async () => {
    await deleteMember(member).catch(() => {});
  });

  test("a genuine recovery link lets the member set a new password", async ({
    page,
    baseURL,
  }) => {
    // Generate the same link Supabase would email.
    const { data, error } = await serviceClient().auth.admin.generateLink({
      type: "recovery",
      email: member.email,
      options: { redirectTo: `${baseURL}/connect/reset-password` },
    });
    expect(error, "generateLink should succeed").toBeNull();

    const actionLink = data?.properties?.action_link;
    test.skip(!actionLink, "Supabase did not return an action link");

    // Following the action link performs the token exchange and lands on the
    // redirectTo with the session in the fragment — the real path.
    await page.goto(actionLink!);
    await page.waitForURL(/\/connect\/reset-password/, { timeout: 20000 });

    const newPassword = "e2e-Rotated-Passw0rd!";
    await expect(page.getByLabel("New password")).toBeVisible({ timeout: 15000 });
    await page.getByLabel("New password").fill(newPassword);
    await page.getByLabel("Confirm new password").fill(newPassword);
    await page.getByRole("button", { name: /Save new password/ }).click();

    // Approved member ⇒ straight to the directory, signed in.
    await expect(page).toHaveURL(/\/connect\/(directory|setup|pending)/, {
      timeout: 20000,
    });

    // The new password must actually work.
    const { createClient } = await import("@supabase/supabase-js");
    const sb = createClient(
      process.env.TEST_SUPABASE_URL!,
      process.env.TEST_SUPABASE_ANON_KEY!,
      { auth: { persistSession: false } }
    );
    const { error: signInErr } = await sb.auth.signInWithPassword({
      email: member.email,
      password: newPassword,
    });
    expect(signInErr, "the new password must authenticate").toBeNull();

    const { error: oldErr } = await sb.auth.signInWithPassword({
      email: member.email,
      password: member.password,
    });
    expect(oldErr, "the old password must stop working").not.toBeNull();
  });

  test("mismatched confirmation is rejected before any request", async ({
    page,
    baseURL,
  }) => {
    const { data } = await serviceClient().auth.admin.generateLink({
      type: "recovery",
      email: member.email,
      options: { redirectTo: `${baseURL}/connect/reset-password` },
    });
    const link = data?.properties?.action_link;
    test.skip(!link, "Supabase did not return an action link");

    await page.goto(link!);
    await page.waitForURL(/\/connect\/reset-password/, { timeout: 20000 });
    await expect(page.getByLabel("New password")).toBeVisible({ timeout: 15000 });

    await page.getByLabel("New password").fill("e2e-Long-Enough-1!");
    await page.getByLabel("Confirm new password").fill("e2e-Different-1!");
    await page.getByRole("button", { name: /Save new password/ }).click();

    await expect(page.getByRole("alert")).toContainText(/don't match/i);
    await expect(page, "must stay on the form").toHaveURL(/reset-password/);
  });
});

test.describe("forgot-password link is reachable from login", () => {
  test("the login page links to the reset flow", async ({ page }) => {
    await page.goto("/connect/login");
    const link = page.getByRole("link", { name: /forgot password/i });
    await expect(link).toBeVisible();
    await link.click();
    await expect(page).toHaveURL(/\/connect\/forgot-password/);
  });
});
